#!/bin/sh
# /docker-entrypoint.d/15-realip-gateway.sh (nginx image hook, runs as root
# before nginx starts).  docs/MCP_DISCOVERY.md "Client IP".
#
# The host nginx reaches this container through the published port
# 127.0.0.1:8080, so the connection arrives from the GATEWAY of the
# container's own docker network (docker-proxy / NAT).  That gateway -- and
# loopback -- are the only peers whose X-Real-IP header we accept; any other
# container on any bridge keeps its own address.  The subnet is not pinned in
# docker-compose.yml, so the gateway is read at start-up from the routing
# table instead of being hard-coded.
#
# Fail closed: no default route found -> trust 127.0.0.1 only (the API then
# counts every visitor as the gateway: one shared bucket, never a spoofable one).
set -eu

OUT=/etc/nginx/realip/trusted.conf
mkdir -p "$(dirname "$OUT")"

# /proc/net/route: Iface Destination Gateway ... in little-endian hex.
GW=$(awk '
  function h(s,   i, v) { v = 0; for (i = 1; i <= 2; i++) v = v * 16 + index("0123456789ABCDEF", toupper(substr(s, i, 1))) - 1; return v }
  NR > 1 && $2 == "00000000" && $3 != "00000000" && length($3) == 8 {
    printf "%d.%d.%d.%d", h(substr($3, 7, 2)), h(substr($3, 5, 2)), h(substr($3, 3, 2)), h(substr($3, 1, 2)); exit
  }' /proc/net/route 2>/dev/null || true)

printf '%s' "$GW" | grep -Eq '^([0-9]{1,3}\.){3}[0-9]{1,3}$' || GW=""
{
  echo "# generated by 15-realip-gateway.sh at container start"
  echo "set_real_ip_from 127.0.0.1;"
  if [ -n "$GW" ]; then
    echo "set_real_ip_from $GW;"
  fi
} > "$OUT.tmp"
mv "$OUT.tmp" "$OUT"

if [ -n "$GW" ]; then
  echo "realip: trusting X-Real-IP from 127.0.0.1 and the network gateway $GW"
else
  echo "realip: no default gateway found; trusting X-Real-IP from 127.0.0.1 only"
fi
