"""The ``switching_table`` card block — built from double pulses, read by the
loss model when ``switching_source`` is ``"spice"``.

Block layout (YAML, appended to the card between two marker comments so the
hand-written card and its comments stay untouched)::

    switching_table:
      basis: "spice:<lib file>@<sha256[:12]>:<subckt>"
      lib_sha256: <full sha256 of the vendor library>
      simulator: "ngspice-46 (KiCad 10.0 shared library), ngbehavior=psa"
      circuit: "datasheet Fig. F double pulse, DUT low side, body-diode freewheel"
      windows: "E_on/E_off Fig. C (10 % V_DS / 10 % I_D); E_fr over t_fr, Fig. B"
      generated: "2026-09-23"
      sets:
        - v_gs_on_V: 18
          v_gs_off_V: 0
          r_g_on_ohm: 2.3          # EXTERNAL
          r_g_off_ohm: 2.3
          l_sigma_nH: 15
          l_gate_nH: 2
          c_sigma_pF: 20
          # [V_dc, T_j, I_off, E_off_uJ, I_on, E_on_uJ, E_fr_uJ]
          rows: [[800, 175, 185.4, 4630, 184.9, 5120, 2890], ...]

Interpolation (:func:`table_energy`): inside one set, per (V_dc, T_j) grid
node, each energy is piecewise-linear in ITS OWN measured current (E_off
against I_off, E_on and E_fr against I_on) with linear extrapolation from the
last two points (flagged above, stated below, clamped at zero); then bilinear
in V_dc and T_j between the grid nodes — linear EXTRApolation in V_dc is
flagged, T_j is clamped to the tabulated span (flagged).  No scaling law is
assumed anywhere: every dependence is what the vendor model produced.
"""
from __future__ import annotations

import datetime as _dt
import math
import re
from pathlib import Path
from typing import Any, Dict, Iterable, List, Optional, Sequence, Tuple

import yaml

__all__ = ["make_set", "make_block", "write_block", "read_block",
           "select_set", "table_energy", "MARK_BEGIN", "MARK_END"]

MARK_BEGIN = ("# >>> switching_table — generated by motor_ai_sim.inverter.spice"
              ".table; do not edit by hand")
MARK_END = "# <<< switching_table"


def _interp1(xs: Sequence[float], ys: Sequence[float], x: float
             ) -> Tuple[float, bool, bool]:
    """Piecewise-linear, linear extrapolation both ends; (y, above, below)."""
    pts = sorted(zip(xs, ys))
    if not pts:
        return 0.0, False, False
    if len(pts) == 1:
        return pts[0][1], x > pts[0][0], x < pts[0][0]
    above, below = x > pts[-1][0], x < pts[0][0]
    if x <= pts[0][0]:
        (x0, y0), (x1, y1) = pts[0], pts[1]
    elif x >= pts[-1][0]:
        (x0, y0), (x1, y1) = pts[-2], pts[-1]
    else:
        k = next(j for j in range(1, len(pts)) if pts[j][0] >= x)
        (x0, y0), (x1, y1) = pts[k - 1], pts[k]
    if x1 == x0:
        return y0, above, below
    return y0 + (y1 - y0) * (x - x0) / (x1 - x0), above, below


def make_set(*, v_gs_on: float, v_gs_off: float, r_g_on: float,
             r_g_off: float, l_sigma_nH: float, l_gate_nH: float,
             c_sigma_pF: float, runs: Iterable[Dict[str, Any]]) -> Dict[str, Any]:
    """One driver/layout set from finished :func:`harness.run_double_pulse`
    results.  Runs whose extraction failed are left out (and counted)."""
    rows: List[List[float]] = []
    dropped = 0
    for r in runs:
        m = r["metrics"]
        c = r["conditions"]
        e_off = m["off"].get("e_J")
        e_on = m["on"].get("e_J")
        e_fr = (m.get("fr") or {}).get("e_fr_J")
        if e_off is None or e_on is None:
            dropped += 1
            continue
        rows.append([round(float(c["v_dd"]), 3), round(float(c["t_j"]), 2),
                     round(float(m["i_off_A"]), 3), round(float(e_off) * 1e6, 2),
                     round(float(m["i_on_A"]), 3), round(float(e_on) * 1e6, 2),
                     round(float(e_fr or 0.0) * 1e6, 2)])
    rows.sort()
    return {"v_gs_on_V": v_gs_on, "v_gs_off_V": v_gs_off,
            "r_g_on_ohm": r_g_on, "r_g_off_ohm": r_g_off,
            "l_sigma_nH": l_sigma_nH, "l_gate_nH": l_gate_nH,
            "c_sigma_pF": c_sigma_pF, "rows": rows, "dropped_runs": dropped}


def make_block(*, model, sets: List[Dict[str, Any]], simulator: str,
               note: str = "") -> Dict[str, Any]:
    return {
        "basis": model.basis,
        "lib_sha256": model.lib_sha256,
        "lib_file": model.lib_name,
        "subckt": model.subckt,
        "simulator": simulator,
        "circuit": ("datasheet Fig. F double pulse: DUT low side, identical "
                    "high side freewheeling in its body diode, L_sigma split "
                    "1/2 + 1/2, "
                    + ("isothermal L1 model at .temp = T_j" if not model.thermal_pins else
                       f"{model.level} model, case pins held at T_j, junction on the "
                       "model's own thermal network (rise < 1 K over the pulses)")),
        "switched_current": ("I_off = I_on = the load current in the gap (freewheel "
                             "current averaged over its last 150 ns)"),
        "windows": ("E_off/E_on: datasheet Fig. C (10 % V_DS to 10 % I_D / "
                    "10 % I_D to 10 % V_DS); E_fr: freewheeling device V*I over "
                    "t_fr of Fig. B (zero crossing to 10 % I_frm)"),
        "generated": _dt.date.today().isoformat(),
        "note": note or ("SECOND source beside the datasheet curves; the loss "
                         "model reads it only with switching_source: spice"),
        "row_columns": ["V_dc", "T_j", "I_off", "E_off_uJ", "I_on", "E_on_uJ", "E_fr_uJ"],
        "sets": sets,
    }


def _dump_block(block: Dict[str, Any]) -> str:
    """YAML with each row on one line (flow), the rest block style."""
    b = dict(block)
    sets = b.pop("sets")
    head = yaml.safe_dump({"switching_table": b}, sort_keys=False,
                          allow_unicode=True, width=100)
    out = [head.rstrip("\n"), "  sets:"]
    for s in sets:
        s = dict(s)
        rows = s.pop("rows")
        first = True
        for k, v in s.items():
            out.append(("  - " if first else "    ") + f"{k}: {yaml.safe_dump(v, default_flow_style=True).strip().rstrip('.').strip()}")
            first = False
        out.append("    rows:")
        for r in rows:
            out.append("      - [" + ", ".join(f"{x:g}" for x in r) + "]")
    return "\n".join(out) + "\n"


def write_block(card_path: Path, block: Dict[str, Any], *,
                switching_source: Optional[str] = None) -> None:
    """Insert or replace the generated block at the end of a card file,
    leaving every hand-written line untouched."""
    p = Path(card_path)
    text = p.read_text(encoding="utf-8")
    pat = re.compile(re.escape(MARK_BEGIN) + r".*?" + re.escape(MARK_END) + r"\n?",
                     re.DOTALL)
    text = pat.sub("", text).rstrip("\n") + "\n"
    body = _dump_block(block)
    if switching_source:
        body = f"switching_source: {switching_source}\n" + body
    text += "\n" + MARK_BEGIN + "\n" + body + MARK_END + "\n"
    # parse check before writing: the card must stay one valid mapping
    doc = yaml.safe_load(text)
    if not isinstance(doc, dict) or "switching_table" not in doc:
        raise ValueError("generated block did not parse back")
    p.write_text(text, encoding="utf-8")


def read_block(doc: Dict[str, Any]) -> Optional[Dict[str, Any]]:
    b = doc.get("switching_table")
    return b if isinstance(b, dict) and b.get("sets") else None


def select_set(block: Dict[str, Any], *, v_gs_off: float,
               r_g_on: Optional[float], r_g_off: Optional[float],
               l_sigma_nH: Optional[float], v_gs_on: Optional[float] = None
               ) -> Tuple[Dict[str, Any], List[str]]:
    """The set that matches the driver; the nearest one, SAID, otherwise."""
    sets = [s for s in block.get("sets") or [] if isinstance(s, dict) and s.get("rows")]
    if not sets:
        raise ValueError("switching_table has no sets")

    def dist(s: Dict[str, Any]) -> float:
        d = 10.0 * abs(float(s.get("v_gs_off_V", 0)) - float(v_gs_off))
        if v_gs_on is not None:
            d += 10.0 * abs(float(s.get("v_gs_on_V", 18)) - float(v_gs_on))
        for key, want in (("r_g_on_ohm", r_g_on), ("r_g_off_ohm", r_g_off)):
            if want is not None:
                d += abs(math.log(max(float(s.get(key, 1)), 1e-3) / max(float(want), 1e-3)))
        if l_sigma_nH is not None:
            d += abs(math.log(max(float(s.get("l_sigma_nH", 15)), 1e-3) / max(float(l_sigma_nH), 1e-3)))
        return d

    best = min(sets, key=dist)
    notes: List[str] = []
    if dist(best) > 1e-9:
        notes.append(
            "no SPICE set for exactly this driver — nearest set used: "
            f"V_GS {best.get('v_gs_off_V')}/{best.get('v_gs_on_V')} V, "
            f"R_G,on {best.get('r_g_on_ohm')} ohm, R_G,off {best.get('r_g_off_ohm')} ohm, "
            f"L_sigma {best.get('l_sigma_nH')} nH")
    return best, notes


def table_energy(block: Dict[str, Any], *, i_d_A: float, v_dc_V: float,
                 t_j_c: float, v_gs_off_V: float = 0.0,
                 r_g_on_ohm: Optional[float] = None,
                 r_g_off_ohm: Optional[float] = None,
                 l_sigma_nH: Optional[float] = None,
                 v_gs_on_V: Optional[float] = None) -> Dict[str, Any]:
    """``{e_on_J, e_off_J, e_fr_J, extrapolated, extrapolated_below, notes}``
    — the same contract as :meth:`DeviceCard.e_switch`."""
    s, notes = select_set(block, v_gs_off=v_gs_off_V, r_g_on=r_g_on_ohm,
                          r_g_off=r_g_off_ohm, l_sigma_nH=l_sigma_nH,
                          v_gs_on=v_gs_on_V)
    rows = [r for r in s["rows"] if len(r) >= 7]
    vs = sorted({float(r[0]) for r in rows})
    ts = sorted({float(r[1]) for r in rows})
    i = max(float(i_d_A), 0.0)
    flags = {"above": False, "below": False, "v_out": False, "t_clamped": False}

    def at(v: float, t: float) -> Dict[str, float]:
        sub = [r for r in rows if float(r[0]) == v and float(r[1]) == t]
        e_off, a1, b1 = _interp1([r[2] for r in sub], [r[3] for r in sub], i)
        e_on, a2, b2 = _interp1([r[4] for r in sub], [r[5] for r in sub], i)
        e_fr, _, _ = _interp1([r[4] for r in sub], [r[6] for r in sub], i)
        flags["above"] |= a1 or a2
        flags["below"] |= b1 or b2
        return {"e_off": max(e_off, 0.0), "e_on": max(e_on, 0.0), "e_fr": max(e_fr, 0.0)}

    def bracket(grid: List[float], x: float, clamp: bool) -> Tuple[float, float, float]:
        if len(grid) == 1:
            return grid[0], grid[0], 0.0
        if clamp:
            x = min(max(x, grid[0]), grid[-1])
        if x <= grid[0]:
            a, b = grid[0], grid[1]
        elif x >= grid[-1]:
            a, b = grid[-2], grid[-1]
        else:
            k = next(j for j in range(1, len(grid)) if grid[j] >= x)
            a, b = grid[k - 1], grid[k]
        return a, b, (x - a) / (b - a) if b != a else 0.0

    tv = float(t_j_c)
    if ts and (tv < ts[0] - 1e-9 or tv > ts[-1] + 1e-9):
        flags["t_clamped"] = True
    vv = float(v_dc_V)
    if vs and (vv < vs[0] - 1e-9 or vv > vs[-1] + 1e-9):
        flags["v_out"] = True
    v0, v1, fv = bracket(vs, vv, clamp=False)
    t0, t1, ft = bracket(ts, tv, clamp=True)
    grid = {(v, t): at(v, t) for v in {v0, v1} for t in {t0, t1}}
    out: Dict[str, Any] = {}
    for k in ("e_on", "e_off", "e_fr"):
        lo = grid[(v0, t0)][k] * (1 - ft) + grid[(v0, t1)][k] * ft
        hi = grid[(v1, t0)][k] * (1 - ft) + grid[(v1, t1)][k] * ft
        out[k + "_J"] = max(lo * (1 - fv) + hi * fv, 0.0) * 1e-6
    notes.insert(0, f"switching energy from the SPICE table ({block.get('basis')}), "
                    f"set R_G,on {s.get('r_g_on_ohm')} / R_G,off {s.get('r_g_off_ohm')} ohm, "
                    f"L_sigma {s.get('l_sigma_nH')} nH, V_GS {s.get('v_gs_off_V')}/{s.get('v_gs_on_V')} V")
    if flags["v_out"]:
        if len(vs) == 1:
            notes.append(f"V_dc {vv:g} V: this set was simulated at {vs[0]:g} V only — "
                         "the energies are HELD at that bus, not scaled")
        else:
            notes.append(f"V_dc {vv:g} V is outside the table's {vs[0]:g}…{vs[-1]:g} V "
                         "— linearly extrapolated")
    if flags["t_clamped"]:
        notes.append(f"T_j {tv:g} degC is outside the table's {ts[0]:g}…{ts[-1]:g} degC — held at the edge")
    if flags["above"]:
        notes.append(f"{i:.0f} A is above the table's highest simulated current — linearly extrapolated")
    out.update({"extrapolated": bool(flags["above"] or flags["v_out"]),
                "extrapolated_below": bool(flags["below"]),
                "notes": notes, "switching_energy_source": "spice_table",
                "spice_set": {k: s.get(k) for k in ("v_gs_on_V", "v_gs_off_V", "r_g_on_ohm",
                                                    "r_g_off_ohm", "l_sigma_nH")}})
    return out
